name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          python -m unittest discover /
 deployment:
     needs: test_suite
     runs-on: ubuntu-latest
     steps:
       - name: Fresh clone & repo install
         uses: appleboy/ssh-action@master
         with:
           #IP address of EC2 instance
           host: 52.201.66.14
           #User you created on the EC2 instance
           username: github-actions
           #Name of the secrets variable where you put your secret key
           key: ${{secrets.SSH_KEY}}
           port: 22
           script: |
             rm -rf squiz
             git clone https://github.com/dhanyavittaldas/kleen-tidy-master.git
             python3.8 -m venv /home/github-actions/squiz/venv
             /home/github-actions/squiz/venv/bin/pip install -r requirements.txt 